# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_click', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
