# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-04 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_click', '0004_auto_20190117_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='market_type',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Close')], default=1),
        ),
    ]
