# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_click', '0005_auto_20190204_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
