# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-24 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_click', '0006_userprofile_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single', models.IntegerField()),
                ('panel', models.IntegerField()),
                ('panel_type', models.IntegerField(choices=[(1, 'Single'), (2, 'Double')], default=1)),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_click.Market')),
            ],
        ),
    ]
