# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-08 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_click', '0007_gameresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw'), (3, 'Win'), (4, 'Play'), (5, 'Loss')], default=0),
        ),
    ]
