# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_click', '0008_auto_20190608_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
