
TRANSACTION_TYPE_DEBIT = 1
TRANSACTION_TYPE_CREDIT = 1

PAYMENT_TYPE_DEPOSIT = 1
PAYMENT_TYPE_WITHDRAW = 2
PAYMENT_TYPE_WIN = 3
PAYMENT_TYPE_PLAY = 4
PAYMENT_TYPE_LOSS = 5
PAYMENT_TYPE_CANCELLED = 6

GAME_STATUS_PENDING = 1
GAME_STATUS_APPROVED = 2

RESULT_STATUS_WIN = 1
RESULT_STATUS_LOSS = 2
RESULT_STATUS_PENDING = 3
RESULT_STATUS_CANCELLED = 4

PANEL_TYPE_SINGLE = 1
PANEL_TYPE_DOUBLE = 2

MARKET_TYPE_OPEN = 1
MARKET_TYPE_CLOSE = 2

GAME_SINGLE_RATE = 9
GAME_JODI_RATE = 90
GAME_SINGLE_PANEL_RATE = 140
GAME_DOUBLE_PANEL_RATE = 280

GAME_TYPE_SINGLE = 1
GAME_TYPE_JODI = 2
GAME_TYPE_SINGLE_PANEL = 3
GAME_TYPE_DOUBLE_PANEL = 4
